[phases.setup]
nixpkgs = ["php", "composer", "nodejs", "npm"]

[phases.build]
commands = [
  "composer install --optimize-autoloader --no-dev",
  "npm install",
  "npm run build"
]

[phases.start]
commands = ["php artisan serve --host=0.0.0.0 --port=$PORT"]
